package perpus;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class KelolaUser extends javax.swing.JFrame {

    private DefaultTableModel tabmode;

    private void tampil_user() {
        User anggota = new User();
        ArrayList<User> allanggota = new ArrayList<>(anggota.read());
        Object[] baris = {"No", "Id", "Nama", "Username", "Password"};
        tabmode = new DefaultTableModel(null, baris);
        table.setModel(tabmode);
        try {
            int i = 1;
            for (User anggota1 : allanggota) {
                int id = anggota1.getIdPerson();
                String nama = anggota1.getNama();
                String username = anggota1.getUsername();
                String password = anggota1.getPassword();
                Object[] data = {i, id, nama, username, password};
                i++;
                tabmode.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Menampilkan data GAGAL", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    public KelolaUser() {
        initComponents();
        tampil_user();
        jPanel1.setBackground(new Color(255, 255, 255, 200)); // mengatur warna JPanel1 agar transparan
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b_tambah = new javax.swing.JButton();
        t_nama = new javax.swing.JTextField();
        t_password = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        b_back = new javax.swing.JButton();
        b_hapus = new javax.swing.JButton();
        b_reset = new javax.swing.JButton();
        t_username = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        t_id = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        b_tambah.setText("Tambah");
        b_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_tambahActionPerformed(evt);
            }
        });
        getContentPane().add(b_tambah);
        b_tambah.setBounds(20, 180, 79, 25);

        t_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_namaActionPerformed(evt);
            }
        });
        getContentPane().add(t_nama);
        t_nama.setBounds(100, 70, 150, 22);

        t_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(t_password);
        t_password.setBounds(100, 140, 150, 22);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(270, 40, 452, 172);

        b_back.setText("back");
        b_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_backActionPerformed(evt);
            }
        });
        getContentPane().add(b_back);
        b_back.setBounds(20, 230, 59, 25);

        b_hapus.setText("Hapus");
        b_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_hapusActionPerformed(evt);
            }
        });
        getContentPane().add(b_hapus);
        b_hapus.setBounds(190, 180, 67, 25);

        b_reset.setText("Reset");
        b_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_resetActionPerformed(evt);
            }
        });
        getContentPane().add(b_reset);
        b_reset.setBounds(110, 180, 65, 25);
        getContentPane().add(t_username);
        t_username.setBounds(100, 110, 150, 22);

        jLabel1.setText("Id");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(25, 45, 32, 16);

        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(25, 75, 70, 16);

        jLabel3.setText("Username");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(25, 110, 70, 16);

        jLabel4.setText("Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(25, 142, 70, 16);

        t_id.setEditable(false);
        getContentPane().add(t_id);
        t_id.setBounds(100, 40, 150, 22);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 40, 230, 130);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/library-750x350.png"))); // NOI18N
        jLabel9.setBorder(javax.swing.BorderFactory.createMatteBorder(20, 0, 20, 0, new java.awt.Color(0, 153, 51)));
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 750, 290);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refresh() {
        tampil_user();
    }

    private void b_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_tambahActionPerformed
        try {
            int id = 0;
            String nama = t_nama.getText();
            String username = t_username.getText();
            String password = t_password.getText();
            int role = 0;
            User user = new User();
            if (user.cekUsername(username) && !"".equals(username)){
                User anggota = new User(0, nama, username, password, role);
                anggota.create();
                reset();
                refresh();
            }else{
                JOptionPane.showMessageDialog(null, "Username Tidak Sesuai", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Menambah data GAGAL", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_b_tambahActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        int tabelBarang = table.getSelectedRow();
        t_id.setText(table.getValueAt(tabelBarang, 1).toString());
        t_nama.setText(table.getValueAt(tabelBarang, 2).toString());
        t_username.setText(table.getValueAt(tabelBarang, 3).toString());
        t_password.setText(table.getValueAt(tabelBarang, 4).toString());
    }//GEN-LAST:event_tableMouseClicked

    private void b_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_backActionPerformed
        this.setVisible(false);
        MenuPustakawan menupustakawan = new MenuPustakawan();
        // mengatur ukuran form
        menupustakawan.setSize(528, 437);
        // mengatur form di posisi tengah
        menupustakawan.setLocationRelativeTo(null);
        // menampilkan form
        menupustakawan.setVisible(true);
    }//GEN-LAST:event_b_backActionPerformed

    private void t_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_passwordActionPerformed

    private void b_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_hapusActionPerformed
        try {
            int id = Integer.parseInt(t_id.getText());
            String nama = t_nama.getText();
            String username = t_username.getText();
            String password = t_password.getText();
            int role = 0;
            User anggota = new User(id, nama, username, password, role);
            anggota.delete();
            reset();
            refresh();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Menghapus data GAGAL", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_b_hapusActionPerformed

    private void t_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_namaActionPerformed

    private void b_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_resetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_b_resetActionPerformed

    private void reset() {
        t_id.setText("");
        t_nama.setText("");
        t_username.setText("");
        t_password.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KelolaUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KelolaUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KelolaUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KelolaUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KelolaUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_back;
    private javax.swing.JButton b_hapus;
    private javax.swing.JButton b_reset;
    private javax.swing.JButton b_tambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField t_id;
    private javax.swing.JTextField t_nama;
    private javax.swing.JTextField t_password;
    private javax.swing.JTextField t_username;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
