package perpus;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

public class MainMenu extends javax.swing.JFrame {

    ResultSet rs;
    
    private Person personLogin;
    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Llogin = new javax.swing.JLabel();
        Lrole = new javax.swing.JLabel();
        b_login = new javax.swing.JButton();
        Luser = new javax.swing.JLabel();
        Lpass = new javax.swing.JLabel();
        c_role = new javax.swing.JComboBox<>();
        Username = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        tgl = new javax.swing.JLabel();
        waktu = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Perpustakaan");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setResizable(false);
        getContentPane().setLayout(null);

        Llogin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Llogin.setForeground(new java.awt.Color(255, 255, 255));
        Llogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Llogin.setText("PERPUSTAKAAN IF E'19");
        getContentPane().add(Llogin);
        Llogin.setBounds(60, 80, 300, 29);

        Lrole.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Lrole.setForeground(new java.awt.Color(255, 255, 255));
        Lrole.setText("Login Sebagai");
        Lrole.setToolTipText("");
        getContentPane().add(Lrole);
        Lrole.setBounds(70, 130, 100, 16);

        b_login.setText("LOGIN");
        b_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_loginActionPerformed(evt);
            }
        });
        getContentPane().add(b_login);
        b_login.setBounds(270, 250, 67, 25);

        Luser.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Luser.setForeground(new java.awt.Color(255, 255, 255));
        Luser.setText("Username");
        getContentPane().add(Luser);
        Luser.setBounds(70, 170, 110, 16);

        Lpass.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Lpass.setForeground(new java.awt.Color(255, 255, 255));
        Lpass.setText("Password");
        getContentPane().add(Lpass);
        Lpass.setBounds(70, 210, 110, 16);

        c_role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User", "Pustawakan", "Admin" }));
        getContentPane().add(c_role);
        c_role.setBounds(220, 130, 130, 22);
        getContentPane().add(Username);
        Username.setBounds(220, 170, 130, 22);
        getContentPane().add(Password);
        Password.setBounds(220, 210, 130, 22);
        getContentPane().add(tgl);
        tgl.setBounds(20, 310, 120, 20);
        getContentPane().add(waktu);
        waktu.setBounds(20, 310, 120, 20);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/fteknik.unmul_20210513_192931_0.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(20, 0, 20, 0, new java.awt.Color(0, 0, 153)));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 430, 357);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void b_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_loginActionPerformed
        try{
            Connection konek = new DBConection().getConnection();
            String sql = "SELECT * FROM person WHERE username='"+ Username.getText()+"' AND password='"+Password.getText()+"'";
            PreparedStatement stat = (PreparedStatement) konek.prepareStatement(sql);
            rs = stat.executeQuery(sql);
            if (rs.next()){
                if (rs.getInt("role")== c_role.getSelectedIndex() && Username.getText().equals(rs.getString("username")) && Password.getText().equals(rs.getString("password"))){
                    ViewDataUserLogin log = new ViewDataUserLogin(rs.getInt("id"),rs.getString("nama"),rs.getString("username"),rs.getString("password"),Integer.parseInt(rs.getString("role")));
                    switch (rs.getInt("role")){
                        case 0:
                            this.setVisible(false);
                            MenuUser menuuser = new MenuUser();
                            // mengatur ukuran form
                            menuuser.setSize(604,385);
                            // mengatur form di posisi tengah
                            menuuser.setLocationRelativeTo(null);
                            // menampilkan form
                            menuuser.setVisible(true);
                            break;
                        case 1:
                            this.setVisible(false);
                            MenuPustakawan menupustakawan = new MenuPustakawan();
                            // mengatur ukuran form
                            menupustakawan.setSize(528,437);
                            // mengatur form di posisi tengah
                            menupustakawan.setLocationRelativeTo(null);
                            // menampilkan form
                            menupustakawan.setVisible(true);
                            break;
                        case 2:
                            this.setVisible(false);
                            MenuAdmin menuadmin = new MenuAdmin();
                            // mengatur ukuran form
                            menuadmin.setSize(458,317);
                            // mengatur form di posisi tengah
                            menuadmin.setLocationRelativeTo(null);
                            // menampilkan form
                            menuadmin.setVisible(true);
                            break;
                    }
                    konek.close();                    
                } else{
                    javax.swing.JOptionPane.showMessageDialog(null, "USERNAME DAN PASWORD TIDAK TERSEDIA"); 
                }   
            }else{
                javax.swing.JOptionPane.showMessageDialog(null, "USERNAME DAN PASWORD ANDA SALAH");
                Username.setText("");
                Password.setText("");
                c_role.setSelectedIndex(0);
                Username.requestFocus();
            }            
        }catch(Exception e){
            javax.swing.JOptionPane.showMessageDialog(null, e);
            Username.setText("");
            Password.setText("");
            c_role.setSelectedIndex(0);
            Username.requestFocus();
        }
    }//GEN-LAST:event_b_loginActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {  
                MainMenu mainmenu = new MainMenu();
                // mengatur ukuran form
                mainmenu.setSize(435,390);
                // mengatur form di posisi tengah
                mainmenu.setLocationRelativeTo(null);
                // menampilkan form
                mainmenu.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Llogin;
    private javax.swing.JLabel Lpass;
    private javax.swing.JLabel Lrole;
    private javax.swing.JLabel Luser;
    private javax.swing.JPasswordField Password;
    private javax.swing.JTextField Username;
    private javax.swing.JButton b_login;
    private javax.swing.JComboBox<String> c_role;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel tgl;
    private javax.swing.JLabel waktu;
    // End of variables declaration//GEN-END:variables
}
