package perpus;

import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class MenuUser extends javax.swing.JFrame {
    
    private DefaultTableModel tabmode;
    
    private void tampil_barang(String sql){
        Object[]baris = {"Id buku", "Judul", "Pengarang", "Penerbit", "Ketersediaan", "Tahun Terbit"};
        tabmode= new DefaultTableModel(null, baris);
        table.setModel(tabmode);
        try {
            Connection konek = new DBConection().getConnection();
            Statement stat = konek.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()){
                String id = hasil.getString("id");
                String judul_buku = hasil.getString("judul_buku");
                String pengarang = hasil.getString("pengarang");
                String penerbit = hasil.getString("penerbit");
                String ketersediaan = hasil.getString("ketersediaan");
                String tahun = hasil.getString("tahun_terbit");
                String[]data = {id, judul_buku, pengarang, penerbit, ketersediaan, tahun};
                tabmode.addRow(data);
            }
            konek.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Tidak Tersedia", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    public MenuUser() {
        initComponents();
        jPanel1.setBackground(new Color(255,255,255,200)); // mengatur warna JPanel1 agar transparan
        String sql = "select * from buku";
        tampil_barang(sql);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        B_cari = new javax.swing.JButton();
        B_datadiri = new javax.swing.JButton();
        B_kunci = new javax.swing.JComboBox<>();
        T_cari = new javax.swing.JTextField();
        B_logout = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        B_pinjam = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        B_cari.setText("Search");
        B_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_cariActionPerformed(evt);
            }
        });
        getContentPane().add(B_cari);
        B_cari.setBounds(147, 105, 73, 25);

        B_datadiri.setText("Data Diri");
        B_datadiri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_datadiriActionPerformed(evt);
            }
        });
        getContentPane().add(B_datadiri);
        B_datadiri.setBounds(487, 105, 101, 25);

        B_kunci.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "judul_buku", "penerbit", "pengarang" }));
        getContentPane().add(B_kunci);
        B_kunci.setBounds(147, 44, 120, 22);
        getContentPane().add(T_cari);
        T_cari.setBounds(147, 74, 120, 22);

        B_logout.setText("Log Out");
        B_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_logoutActionPerformed(evt);
            }
        });
        getContentPane().add(B_logout);
        B_logout.setBounds(487, 289, 101, 25);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(12, 148, 576, 128);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Kata Kunci");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(12, 77, 80, 16);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Cari Berdasarkan");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(12, 47, 120, 16);

        B_pinjam.setText("Data Pinjam");
        B_pinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_pinjamActionPerformed(evt);
            }
        });
        getContentPane().add(B_pinjam);
        B_pinjam.setBounds(487, 73, 101, 25);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 30, 580, 290);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/depositphotos_464202980-stock-illustration-vector-background-from-books-in.jpg"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(20, 0, 20, 0, new java.awt.Color(0, 153, 0)));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 600, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_cariActionPerformed
        String sql = "SELECT * FROM buku WHERE "+B_kunci.getSelectedItem().toString()+" LIKE '%"+T_cari.getText()+"%'";
        tampil_barang(sql);        
    }//GEN-LAST:event_B_cariActionPerformed

    private void B_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_logoutActionPerformed
        this.setVisible(false);
        MainMenu mainmenu = new MainMenu();
        // mengatur ukuran form
        mainmenu.setSize(435,390);
        // mengatur form di posisi tengah
        mainmenu.setLocationRelativeTo(null);
        // menampilkan form
        mainmenu.setVisible(true);
    }//GEN-LAST:event_B_logoutActionPerformed

    private void B_datadiriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_datadiriActionPerformed
        this.setVisible(false);
        ViewDataUserLogin datadiri = new ViewDataUserLogin();
        // mengatur ukuran form
        datadiri.setSize(427,384);
        // mengatur form di posisi tengah
        datadiri.setLocationRelativeTo(null);
        // menampilkan form
        datadiri.setVisible(true);
    }//GEN-LAST:event_B_datadiriActionPerformed

    private void B_pinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_pinjamActionPerformed
        this.setVisible(false);
        ViewPeminjaman pinjam = new ViewPeminjaman();
        // mengatur ukuran form
        pinjam.setSize(700,386);
        // mengatur form di posisi tengah
        pinjam.setLocationRelativeTo(null);
        // menampilkan form
        pinjam.setVisible(true);
    }//GEN-LAST:event_B_pinjamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MenuUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_cari;
    private javax.swing.JButton B_datadiri;
    private javax.swing.JComboBox<String> B_kunci;
    private javax.swing.JButton B_logout;
    private javax.swing.JButton B_pinjam;
    private javax.swing.JTextField T_cari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
